services:
  postgres:
    image: postgres:latest
    restart: always

    container_name: postgres
    hostname: postgres

    env_file:
      - .env

    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}

    ports:
      - "${PG_PORT}:5432"

    networks:
      - my-network

networks:
  my-network:
    driver: bridge