name: tests

on:
    push

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: ['1.22.2']
        steps:
            -
                name: Check repository
                uses: actions/checkout@v3
            -
                name: Start dependecies in docker-compose
                uses: hoverkraft-tech/compose-action@v1.5.1
                with:
                    compose-file: "docker-compose-test.yml"
            -
                name: Setup Go ${{ matrix.go-version }}
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ matrix.go-version }}
            -
                name: Test user service
                run: go test ./user-service/...
